In [1]:
import numpy as np

In [6]:
#a função array cria um array numpy
arr2 = np.array([1, 3, 6, 10, 15])

In [7]:
print(arr2)

[ 1  3  6 10 15]


In [9]:
#usando metodos do array
arr2.cumsum()

array([ 1,  4, 10, 20, 35], dtype=int32)

In [10]:
arr2.cumprod()

array([   1,    3,   18,  180, 2700], dtype=int32)

In [11]:
arr3 = np.arange(0, 50, 5)
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [12]:
np.shape(arr3)

(10,)

In [13]:
#cria um array preenchido com zeros
arr4 = np.zeros(10)
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
#retorna 1 nas posiçoes em diagonal e 0 no restante
#matriz diagonal
arr5 = np.eye(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
#os valores passados como parametro, forma uma diagonal
arr6 = np.diag(np.array([1, 2, 3, 4]))
arr6

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [18]:
#array com valores booleanos
arr7 = np.array([True, False, True, False])
arr7

array([ True, False,  True, False])

In [19]:
#array de strings
arr8 = np.array(['Lingagem Python', 'Linguagem R', 'Linguagem C'])
print(arr8)

['Lingagem Python' 'Linguagem R' 'Linguagem C']


In [22]:
#A funçao linspace do numpy é usada para criar uma sequencia de numeros igualmente espaçados dentro de um intervalo especifico
print(np.linspace(0 , 10))
print('\n')
print(np.linspace(0, 10, 15))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [24]:
#a funcao logspace é usada para criar uma sequencia de numeros igualmente espaçados em escala logaritma dentro de um intervalo especifico
print(np.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]
