In [2]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [4]:
print(arr1.shape)

(2, 3)


In [5]:
#criando uma lista 2x3 apenas com numeros 1
arr2 = np.ones((2,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#lista de listas
lista = [[13,81,22], [0,34,59], [21,48,94]]

In [7]:
#a funcao matrix cria uma matriz a partir de uma lista de listas
arr3 = np.matrix(lista)
print(arr3)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [8]:
print(arr3.size)

9


In [9]:
#indexação da matriz (linha, coluna)
arr3[2,1]

48

In [10]:
arr3[0:2,2]

matrix([[22],
        [59]])

In [11]:
arr3[1,]  #linha 1

matrix([[ 0, 34, 59]])

In [12]:
#alterando elemento da matriz
arr3[1,0] = 100
print(arr3)

[[ 13  81  22]
 [100  34  59]
 [ 21  48  94]]


In [13]:
#itemsize de um array numpy é um atributo que retorna o tamanho em bytes de cada elemento do array. O itemsize representa o numero de bytes necessarios para armazenar cada valor do array numpy

arr4 = np.array([[24,76,92,14], [47,35,89,2]], dtype=float)
print(arr4)

[[24. 76. 92. 14.]
 [47. 35. 89.  2.]]


In [14]:
arr4.itemsize

8

In [15]:
arr4.nbytes

64

In [16]:
arr4.ndim   #dimensoes

2

#### Manipulando objetos de 3 e 4 dimensoes

In [17]:
arr_3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [18]:
arr_3d.ndim

3

In [ ]:
arr_3d.shape  

(2, 3, 4)

In [20]:
arr_3d[0, 2, 1]

10