In [7]:
import numpy as np

### Criando array

In [8]:
#array numpy muito mais eficiente, veloz e versatil que uma lista normal

arr1 = np.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [9]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [10]:
arr1.shape

#shape 9, > 1D , shape 2,3 >> 2D, shape 4,3,2 >> 3D

(9,)

### Indexação em arrays numpy

In [11]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [12]:
arr1[4]

48

In [13]:
arr1[1:4]

array([21, 32, 43])

In [14]:
arr1[1:4+1]

array([21, 32, 43, 48])

In [15]:
#cria uma lista de indices
indices = [1, 2, 5, 6]

In [16]:
arr1[indices]

array([21, 32, 15, 76])

In [19]:
#mascara booleana para os elementos pares
mask = (arr1 % 2 == 0)

In [20]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [18]:
arr1[mask]

array([10, 32, 48, 76])

In [21]:
#alterando um elemento do array
arr1[0] = 100
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [22]:
#nao é possivel incluir elemento de outro tipo
try:
    arr1[0] = 'Novo elemento'

except:
    print('Operação não permitida')

Operação não permitida
