In [1]:
import numpy as np

In [4]:
arr1 = np.arange(1, 10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [5]:
#soma dos elementos
np.sum(arr1)

45

In [6]:
#produto
np.prod(arr1)

362880

In [7]:
#soma acumulada dos elementos
np.cumsum(arr1)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [8]:
arr2 = np.array([3, 2, 1])
arr3 = np.array([1, 2, 3])

In [9]:
#soma dos array
arr4 = np.add(arr2, arr3)

In [11]:
print(arr4)

[4 4 4]


In [20]:
#para multiplicar matrizes podemos usar a função dot() ou o operador @
arr5 = np.array([[1, 2], [3, 4]])
arr6 = np.array([[5, 6], [0, 7]])

In [21]:
print(arr6)

[[5 6]
 [0 7]]


In [22]:
#multiplicação
arr7 = np.dot(arr5, arr6)
print(arr7)

[[ 5 20]
 [15 46]]


In [23]:
arr8 = arr5 @ arr6
print(arr8)

[[ 5 20]
 [15 46]]
