In [1]:
import numpy as np

In [ ]:
arr1 = np.diag(np.arange(3))    #matriz com os valores na diagonal
print(arr1)

[[0 0 0]
 [0 1 0]
 [0 0 2]]


In [4]:
arr1[2,2]

2

In [5]:
arr1[1]

array([0, 1, 0])

In [7]:
arr1[:,2]

array([0, 0, 2])

In [8]:
#[start:end:step]
arr1[2:9:3]

array([[0, 0, 2]])

In [10]:
#cria 2 array
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [11]:
#comparação item a item
a == b

array([False,  True, False,  True])

In [12]:
#comparação global
arr2 = np.arange(10)

np.array_equal(arr1, arr2)

False

In [13]:
arr2.min()

0

In [14]:
arr2.max()

9

In [19]:
#somando um valor a cada elemento do array
arr3 = np.array([1, 2, 3]) +1.5
print(arr3)

[2.5 3.5 4.5]


In [17]:
#arredondando
np.around(arr3)

array([2., 4., 4.])

In [20]:
arr4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr4)

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
#metodo flatten é usado para criar uma copia unidimensional de um array multidimensional
arr5 = arr4.flatten() 
print(arr5)

[1 2 3 4 5 6 7 8]


In [23]:
#repetindo os elementos de um array
arr6 = np.array([1, 2, 3])

np.repeat(arr6, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [25]:
#repetindo as combinações
np.tile(arr6, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [26]:
#copia de array
arr7 = np.copy(arr6)

In [27]:
print(arr7)

[1 2 3]
